name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t vijainirmal1/springboot-docker-helloworld .
      - name: Publish image to docker hub
        run: docker push vijainirmal1/springboot-docker-helloworld:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from docker hub
        run: sudo docker pull vijainirmal1/springboot-docker-helloworld:latest
      - name: Delete old container
        run: sudo docker rm -f springboot-docker-helloworld-container
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name springboot-docker-helloworld-container vijainirmal1/springboot-docker-helloworld