name: Deploy to EC2

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }} #ADD .pem secrets as variable
          HOST: ${{ secrets.EC2_HOST }} #ADD public ip / DNS of ec2 instance as variable
          USER: ${{ secrets.EC2_USER }} #ADD image name (ubuntu) of ec2 instance as variable
        run: |
          echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '
          echo "Current directory: $(pwd)"
          echo "Listing home directory:"
          ls -la ~